/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ISPHookInterface extends utils.Interface {
  contractName: "ISPHook";
  functions: {
    "didReceiveAttestation(address,uint64,uint64,bytes)": FunctionFragment;
    "didReceiveRevocation(address,uint64,uint64,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "didReceiveAttestation",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "didReceiveRevocation",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "didReceiveAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "didReceiveRevocation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISPHook extends BaseContract {
  contractName: "ISPHook";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISPHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "didReceiveAttestation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "didReceiveAttestation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "didReceiveRevocation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "didReceiveRevocation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "didReceiveAttestation(address,uint64,uint64,bytes)"(
    attester: string,
    schemaId: BigNumberish,
    attestationId: BigNumberish,
    extraData: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "didReceiveAttestation(address,uint64,uint64,address,uint256,bytes)"(
    attester: string,
    schemaId: BigNumberish,
    attestationId: BigNumberish,
    resolverFeeERC20Token: string,
    resolverFeeERC20Amount: BigNumberish,
    extraData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "didReceiveRevocation(address,uint64,uint64,bytes)"(
    attester: string,
    schemaId: BigNumberish,
    attestationId: BigNumberish,
    extraData: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "didReceiveRevocation(address,uint64,uint64,address,uint256,bytes)"(
    attester: string,
    schemaId: BigNumberish,
    attestationId: BigNumberish,
    resolverFeeERC20Token: string,
    resolverFeeERC20Amount: BigNumberish,
    extraData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "didReceiveAttestation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "didReceiveAttestation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "didReceiveRevocation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "didReceiveRevocation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    "didReceiveAttestation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "didReceiveAttestation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "didReceiveRevocation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "didReceiveRevocation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "didReceiveAttestation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "didReceiveAttestation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "didReceiveRevocation(address,uint64,uint64,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      extraData: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "didReceiveRevocation(address,uint64,uint64,address,uint256,bytes)"(
      attester: string,
      schemaId: BigNumberish,
      attestationId: BigNumberish,
      resolverFeeERC20Token: string,
      resolverFeeERC20Amount: BigNumberish,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
