/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVersionable, IVersionableInterface } from "../IVersionable";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IVersionable__factory {
  static readonly abi = _abi;
  static createInterface(): IVersionableInterface {
    return new utils.Interface(_abi) as IVersionableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVersionable {
    return new Contract(address, _abi, signerOrProvider) as IVersionable;
  }
}
